version: "3.8"

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
services:
  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    restart: always
    ports:
      - ${JUPYTER_PORT}:8888
    volumes:
      - shared-workspace:/opt/workspace
  spark-master:
    image: spark-master
    container_name: spark-master
    restart: always
    ports:
      - ${SPARK_MASTER_WEBUI_PORT}:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    restart: always
    environment:
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
    ports:
      - ${SPARK_WORKER_WEBUI_PORT}:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
